"""Generate openvm/src/zkvm_accel/bls12_381_map_constants.zig from py_ecc.

py_ecc is the library EELS uses for EIP-2537 MAP_FP_TO_G1 / MAP_FP2_TO_G2, so
the map-to-curve code takes its constants from the same source. Run with a
Python that has py_ecc installed (e.g. execution-specs' venv):

    python openvm/scripts/gen_bls12_381_map_constants.py \
        > openvm/src/zkvm_accel/bls12_381_map_constants.zig
"""

from py_ecc.optimized_bls12_381 import constants as C


def le(n, nbytes, indent):
    assert 0 <= n < 1 << (8 * nbytes), (n, nbytes)
    b = n.to_bytes(nbytes, "little")
    pad = " " * indent
    rows = [", ".join(f"0x{x:02x}" for x in b[i : i + 8]) for i in range(0, nbytes, 8)]
    return ".{\n" + "".join(f"{pad}    {r},\n" for r in rows) + pad + "}"


def fq(x, indent=0):
    return le(int(x.n), 48, indent)


def fp2(x, indent=0):
    c0, c1 = x.coeffs
    return le(int(c0) + (int(c1) << 384), 96, indent)


out = [
    "// Generated by openvm/scripts/gen_bls12_381_map_constants.py from py_ecc, the",
    "// library EELS uses for EIP-2537 MAP_FP_TO_G1 / MAP_FP2_TO_G2. Do not edit by hand.",
    "// All values little-endian; Fp2 values are c0 || c1.",
    "",
]


def scalar(name, nbytes, body):
    out.append(f"pub const {name}: [{nbytes}]u8 align(8) = {body};\n")


def table(name, nbytes, elems, enc):
    body = ".{\n" + "".join(f"    {enc(k, 4)},\n" for k in elems) + "}"
    out.append(f"pub const {name}: [{len(elems)}][{nbytes}]u8 align(8) = {body};\n")


POLYS = ["X_NUM", "X_DEN", "Y_NUM", "Y_DEN"]

# G1: simplified SWU onto the 11-isogenous curve, then the 11-isogeny.
scalar("ISO_11_A", 48, fq(C.ISO_11_A))
scalar("ISO_11_B", 48, fq(C.ISO_11_B))
scalar("ISO_11_Z", 48, fq(C.ISO_11_Z))
scalar("SQRT_MINUS_11_CUBED", 48, fq(C.SQRT_MINUS_11_CUBED))
scalar("P_MINUS_3_DIV_4", 48, le(C.P_MINUS_3_DIV_4, 48, 0))
for name, coeffs in zip(POLYS, C.ISO_11_MAP_COEFFICIENTS):
    table(f"ISO_11_{name}", 48, coeffs, fq)

# G2: simplified SWU onto the 3-isogenous curve, then the 3-isogeny.
scalar("ISO_3_A", 96, fp2(C.ISO_3_A))
scalar("ISO_3_B", 96, fp2(C.ISO_3_B))
scalar("ISO_3_Z", 96, fp2(C.ISO_3_Z))
scalar("P_MINUS_9_DIV_16", 96, le(C.P_MINUS_9_DIV_16, 96, 0))
for name, coeffs in zip(POLYS, C.ISO_3_MAP_COEFFICIENTS):
    table(f"ISO_3_{name}", 96, coeffs, fp2)
table("ETAS", 96, C.ETAS, fp2)
table("POSITIVE_EIGHTH_ROOTS_OF_UNITY", 96, C.POSITIVE_EIGHTH_ROOTS_OF_UNITY, fp2)

# Cofactor clearing by multiplication (py_ecc multiply_clear_cofactor_G1/G2).
h1 = (C.H_EFF_G1.bit_length() + 7) // 8
h2 = (C.H_EFF_G2.bit_length() + 7) // 8
scalar("H_EFF_G1", h1, le(C.H_EFF_G1, h1, 0))
scalar("H_EFF_G2", h2, le(C.H_EFF_G2, h2, 0))

print("\n".join(out), end="")
